Add category field and related endpoints to recordings
SunbirdAI/noise-sensors-monitoring pull request #32
Opened 2022-03-10 12:08 UTC by NLSanyu

2022-03-16 10:36 UTC, NLSanyu commented on recordings/urls.py
> +    path('edit/<int:pk>', UpdateDeviceRecordingView.as_view(), name='edit_recording'),
@cmplx-xyttmt I need your view on this:
In this `edit recording` URL, I'm using the primary key of the recording as the identifier to know what recording to edit.
However, I think the audio classification model thing (wherever it will be hosted), and  even our S3 storage (where the recording is stored) both don't know or store the ids of these recordings.
In that case, what do you think we can use to identify a recording to edit?

2022-03-16 16:21 UTC, cmplx-xyttmt commented on recordings/urls.py
> +    path('edit/<int:pk>', UpdateDeviceRecordingView.as_view(), name='edit_recording'),
I think this is fine ... I believe the way it will work is that the classifier will fetch a batch of audio files (or we have a script that sends them to the classifier) from this API rather than getting them directly from s3. So it will know the IDs and the s3 url.

2022-03-16 16:21 UTC, cmplx-xyttmt approved these changes
LGTM...you can merge it in when ready

2022-03-16 16:35 UTC, NLSanyu commented on recordings/urls.py
> +    path('edit/<int:pk>', UpdateDeviceRecordingView.as_view(), name='edit_recording'),
Alright, thanks

2022-03-16 16:51 UTC, cmplx-xyttmt approved these changes
Left some comments.

2022-03-16 16:51 UTC, cmplx-xyttmt commented on recordings/views.py
> +            device__id=self.kwargs['pk']
This is an inefficient way of getting recordings for a specific device. Same reason the metrics endpoint was taking long at first. 

It's better to use the device model for this and use a viewset. For reference, see [this serializer](https://github.com/SunbirdAI/noise-sensors-monitoring/blob/2886364df0a6a91f94257c1c32debc783c2cfc9a/devices/serializers.py#L26) and the [corresponding viewset](https://github.com/SunbirdAI/noise-sensors-monitoring/blob/2886364df0a6a91f94257c1c32debc783c2cfc9a/devices/views.py#L25)

2022-03-16 16:51 UTC, cmplx-xyttmt commented on recordings/views.py
> +    def get_queryset(self):
This will probably also have the same inefficiency issue (has to go through all the recordings to find the specific one with this primary key).

Maybe try using `lookup_field` instead of this `get_queryset` function. i.e

```
class UpdateDeviceRecordingView(UpdateAPIView):
    queryset = Recording.objects.all()
    serializer_class = RecordingSerializer
    lookup_field = 'pk'
```

I'm not 100% sure if this is faster though or if there's is an issue in the first place. Might have to test it when we merge.

2022-03-16 16:54 UTC, cmplx-xyttmt requested changes
View previous review... sorry for the misclicks

2022-03-16 16:59 UTC, NLSanyu commented
> View previous review... sorry for the misclicks

It's okay

I've seen the above review and they make sense......I'll change the code accordingly. Thanks.

2022-03-23 14:25 UTC, NLSanyu commented
@cmplx-xyttmt can this be merged?

2022-03-23 17:17 UTC, cmplx-xyttmt approved these changes
looks good, great work

2022-03-23 17:17 UTC, merged