Create endpoint that receives day-time, hourly and night-time metrics from AWS IoT
SunbirdAI/noise-sensors-monitoring pull request #50
Opened 2022-11-10 18:27 UTC by NLSanyu

This PR creates an endpoint that receives day-time, hourly and night-time metrics from AWS IoT, then aggregates the data and stores it in the DailyAggregate and HourlyAggregate model tables

### How to test:

Send an POST API request to *.../analysis/receive_iot_data/*, with a request body formatted as follows:
```
{
    "type": "hourly",
    "data": [...the list of records]
}
```

### Example:
<img width="909" alt="Screenshot 2022-11-10 at 18 42 55" src="https://user-images.githubusercontent.com/37118361/201179857-9c514656-c762-474f-9cf4-cd14822d29d7.png">

2022-11-10 18:41 UTC, NLSanyu commented
@cmplx-xyttmt this code might need some refactoring (I have a million ideas on how to refactor and optimize it), but for now, it does the task as it is supposed to 😆

2022-11-11 08:33 UTC, cmplx-xyttmt requested changes
Requested 1 change

2022-11-11 08:33 UTC, cmplx-xyttmt commented on analysis/models.py
>  class DailyAggregate(models.Model):
@NLSanyu, I think there should also be a field here that says whether it's daytime or nighttime aggregate

2022-11-11 11:23 UTC, NLSanyu commented on analysis/models.py
>  class DailyAggregate(models.Model):
This is going to sound strange, but I've been struggling for 15 minutes over what name to give this field 😅

2022-11-11 11:24 UTC, NLSanyu commented on analysis/models.py
>  class DailyAggregate(models.Model):
> @NLSanyu, I think there should also be a field here that says whether it's daytime or nighttime aggregate

This is going to sound strange, but I've been struggling for 15 minutes over what name to give this field 😅

2022-11-11 13:14 UTC, cmplx-xyttmt approved these changes

2022-11-11 13:15 UTC, merged